# Generated by Django 4.2.7 on 2023-11-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 20:00:00', verbose_name='Временная метка'),
            preserve_default=False,
        ),
    ]
