# Generated by Django 4.2.7 on 2023-11-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_application_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='image',
        ),
        migrations.RemoveField(
            model_name='application',
            name='state',
        ),
    ]
