# Generated by Django 4.2.7 on 2023-11-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_application_image_remove_application_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('new', 'Новая'), ('progress', 'Принято в работу'), ('completed', 'Выполнено')], default='new', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
