# Generated by Django 4.2.7 on 2023-11-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_application_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
