# Generated by Django 4.2.7 on 2023-11-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_application_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='image',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='image_created',
            field=models.ImageField(blank=True, upload_to='images_created/', verbose_name='Созданная работа'),
        ),
    ]
